CC = gcc

algs: gcdExt.c multiplacativeInverse.c squareNmultiply.c
	gcc -o ExtendedEuclideAlg gcdExt.c
	gcc -o MultiplicativeInverseAlg multiplacativeInverse.c 
	gcc -o SquareAndMultiply squareNmultiply.c 

clean: 
	rm -f *.o ExtendedEuclideAlg MultiplicativeInverseAlg SquareAndMultiply