CC = gcc

algs: gcdExt.c multiplicativeInverse.c squareNmultiply.c
	gcc -o ExtendedEuclideAlg gcdExt.c
	gcc -o MultiplicativeInverseAlg multiplicativeInverse.c 
	gcc -o SquareAndMultiply squareNmultiply.c 
	gcc -o Gcd gcd.c 

clean: 
	rm -f *.o ExtendedEuclideAlg MultiplicativeInverseAlg SquareAndMultiply